import type { ExecutionState } from "./types.ts";

const transitions: Readonly<Record<ExecutionState, readonly ExecutionState[]>> = {
  REQUESTED: ["PRINCIPAL_RESOLVED", "EXCEPTION"],
  PRINCIPAL_RESOLVED: ["ASSET_RESOLVED", "EXCEPTION"],
  ASSET_RESOLVED: ["ENTITLEMENT_RESOLVED", "EXCEPTION"],
  ENTITLEMENT_RESOLVED: ["ROUTE_QUOTED", "EXCEPTION"],
  ROUTE_QUOTED: ["WARDEN_PENDING", "EXCEPTION"],
  WARDEN_PENDING: ["AUTHORIZED", "EXCEPTION"],
  AUTHORIZED: ["FUNDS_RESERVED", "EXCEPTION"],
  FUNDS_RESERVED: ["CAPABILITY_ISSUED", "EXCEPTION"],
  CAPABILITY_ISSUED: ["DISPATCHED", "EXCEPTION"],
  DISPATCHED: ["RUNNING", "EXCEPTION"],
  RUNNING: ["METERING", "EXCEPTION"],
  METERING: ["OUTPUT_OBSERVED", "EXCEPTION"],
  OUTPUT_OBSERVED: ["EFFECT_VERIFIED", "EXCEPTION"],
  EFFECT_VERIFIED: ["ASSET_REGISTERED", "EXCEPTION"],
  ASSET_REGISTERED: ["SETTLED", "EXCEPTION"],
  SETTLED: ["CLOSED"],
  EXCEPTION: ["RECONCILIATION", "CLOSED"],
  RECONCILIATION: ["RECOVERY", "COMPENSATION", "CLOSED"],
  RECOVERY: ["DISPATCHED", "CLOSED"],
  COMPENSATION: ["CLOSED"],
  CLOSED: [],
};

export function assertTransition(from: ExecutionState, to: ExecutionState): void {
  if (!transitions[from].includes(to)) {
    throw new Error(`INVALID_EXECUTION_TRANSITION:${from}->${to}`);
  }
}
