const classifications = [
  "PUBLIC",
  "CUSTOMER",
  "PARTNER",
  "WORKFORCE",
  "MANAGEMENT",
  "GOVERNED_INTERNAL",
  "CONFIDENTIAL",
  "RESTRICTED",
] as const;

const transports = [
  "IN_MEMORY",
  "WEB",
  "APP",
  "EMAIL",
  "SMS",
  "WHATSAPP",
  "SLACK",
  "MARKETPLACE_API",
  "MCP",
  "PRIVATE_SERVICE",
] as const;

const actions = [
  "ACKNOWLEDGE",
  "COMMENT",
  "SUBSCRIBE",
  "REQUEST_ACCESS",
  "PROPOSE_CHANGE",
  "OPEN_API",
  "FORK",
  "ACCEPT",
  "REJECT",
  "REQUEST_REVIEW",
  "EXECUTE_BOUNDED_ACTION",
] as const;

const publicationTypes = [
  "ARTICLE",
  "BULLETIN",
  "ALERT",
  "STATUS",
  "PROPOSAL",
  "REQUEST",
  "TECHNICAL_NOTICE",
] as const;

const boardStatuses = [
  "DRAFT",
  "PREPARED",
  "PENDING_ADMISSION",
  "ADMITTED",
  "ESCALATED",
  "DENIED",
  "PUBLISHED",
  "OBSERVED",
  "ACKNOWLEDGED",
  "ACTED_ON",
  "SUPERSEDED",
  "WITHDRAWN",
  "EXPIRED",
  "ARCHIVED",
] as const;

const stringArray = { type: "array", items: { type: "string", minLength: 1 } } as const;
const classificationArray = {
  type: "array",
  minItems: 1,
  uniqueItems: true,
  items: { type: "string", enum: classifications },
} as const;
const actionArray = {
  type: "array",
  uniqueItems: true,
  items: { type: "string", enum: actions },
} as const;

export const channelV1Schema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://virtualsilkroad.local/schemas/channel-v1.schema.json",
  type: "object",
  additionalProperties: false,
  required: [
    "channelRef",
    "ownerContextRef",
    "subjectScopeRef",
    "status",
    "allowedClassifications",
    "routeRefs",
    "version",
    "createdAt",
  ],
  properties: {
    channelRef: { type: "string", minLength: 1 },
    ownerContextRef: { type: "string", minLength: 1 },
    subjectScopeRef: { type: "string", minLength: 1 },
    status: { type: "string", enum: ["ACTIVE", "INACTIVE", "ARCHIVED"] },
    allowedClassifications: classificationArray,
    routeRefs: stringArray,
    version: { type: "integer", minimum: 1 },
    createdAt: { type: "string" },
  },
} as const;

export const headerBoardV1Schema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://virtualsilkroad.local/schemas/header-board-v1.schema.json",
  type: "object",
  additionalProperties: false,
  required: [
    "headerBoardRef",
    "channelRef",
    "publicationType",
    "subjectRef",
    "sourceEventRefs",
    "publisherPrincipalRef",
    "publisherCapacityRef",
    "audiencePolicyRef",
    "classification",
    "effectiveFrom",
    "status",
    "actionCapabilities",
    "payload",
    "fieldClassifications",
    "correlationId",
  ],
  properties: {
    headerBoardRef: { type: "string", minLength: 1 },
    channelRef: { type: "string", minLength: 1 },
    publicationType: { type: "string", enum: publicationTypes },
    subjectRef: { type: "string", minLength: 1 },
    sourceEventRefs: { ...stringArray, minItems: 1 },
    publisherPrincipalRef: { type: "string", minLength: 1 },
    publisherCapacityRef: { type: "string", minLength: 1 },
    audiencePolicyRef: { type: "string", minLength: 1 },
    classification: { type: "string", enum: classifications },
    effectiveFrom: { type: "string" },
    effectiveUntil: { type: "string" },
    status: { type: "string", enum: boardStatuses },
    actionCapabilities: actionArray,
    payload: { type: "object" },
    fieldClassifications: {
      type: "object",
      additionalProperties: { type: "string", enum: classifications },
    },
    supersedesRef: { type: "string", minLength: 1 },
    correlationId: { type: "string", minLength: 1 },
  },
} as const;

export const publicationAdmissionV1Schema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://virtualsilkroad.local/schemas/publication-admission-v1.schema.json",
  type: "object",
  additionalProperties: false,
  required: [
    "requestRef",
    "headerBoardRef",
    "channelRef",
    "publisherPrincipalRef",
    "representedPrincipalRef",
    "publisherCapacityRef",
    "contextRef",
    "programRef",
    "sourceEventRefs",
    "classification",
    "routeRefs",
    "actionCapabilities",
    "authorityRefs",
    "policyRefs",
    "representationSourceRefs",
    "evidenceReadinessRef",
    "requestedAt",
    "correlationId",
  ],
  properties: {
    requestRef: { type: "string", minLength: 1 },
    headerBoardRef: { type: "string", minLength: 1 },
    channelRef: { type: "string", minLength: 1 },
    publisherPrincipalRef: { type: "string", minLength: 1 },
    representedPrincipalRef: { type: "string", minLength: 1 },
    publisherCapacityRef: { type: "string", minLength: 1 },
    contextRef: { type: "string", minLength: 1 },
    programRef: { type: "string", minLength: 1 },
    sourceEventRefs: { ...stringArray, minItems: 1 },
    classification: { type: "string", enum: classifications },
    routeRefs: { ...stringArray, minItems: 1 },
    actionCapabilities: actionArray,
    authorityRefs: stringArray,
    policyRefs: stringArray,
    representationSourceRefs: stringArray,
    evidenceReadinessRef: { type: "string", minLength: 1 },
    requestedAt: { type: "string" },
    correlationId: { type: "string", minLength: 1 },
  },
} as const;

export const publicationReceiptV1Schema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://virtualsilkroad.local/schemas/publication-receipt-v1.schema.json",
  type: "object",
  additionalProperties: false,
  required: [
    "receiptRef",
    "headerBoardRef",
    "channelRef",
    "routeRef",
    "sourceEventRefs",
    "riverReservationRef",
    "wardenDecisionRef",
    "state",
    "payloadDigest",
    "observedAt",
    "correlationId",
  ],
  properties: {
    receiptRef: { type: "string", minLength: 1 },
    headerBoardRef: { type: "string", minLength: 1 },
    channelRef: { type: "string", minLength: 1 },
    routeRef: { type: "string", minLength: 1 },
    sourceEventRefs: { ...stringArray, minItems: 1 },
    riverReservationRef: { type: "string", minLength: 1 },
    wardenDecisionRef: { type: "string", minLength: 1 },
    state: { type: "string", enum: ["DELIVERED", "DELIVERY_FAILED", "DELIVERY_UNCERTAIN"] },
    providerReceiptRef: { type: "string", minLength: 1 },
    payloadDigest: { type: "string", pattern: "^sha256:[a-f0-9]{64}$" },
    observedAt: { type: "string" },
    correlationId: { type: "string", minLength: 1 },
  },
} as const;

export const serviceRouteV1Schema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://virtualsilkroad.local/schemas/service-route-v1.schema.json",
  type: "object",
  additionalProperties: false,
  required: [
    "routeRef",
    "channelRef",
    "serviceRef",
    "transport",
    "endpoint",
    "status",
    "allowedClassifications",
  ],
  properties: {
    routeRef: { type: "string", minLength: 1 },
    channelRef: { type: "string", minLength: 1 },
    serviceRef: { type: "string", minLength: 1 },
    transport: { type: "string", enum: transports },
    endpoint: { type: "string", minLength: 1 },
    status: { type: "string", enum: ["ACTIVE", "INACTIVE"] },
    allowedClassifications: classificationArray,
  },
} as const;

export const serviceDescriptorV1Schema = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://virtualsilkroad.local/schemas/service-descriptor-v1.schema.json",
  type: "object",
  additionalProperties: false,
  required: [
    "serviceRef",
    "handle",
    "transport",
    "endpoint",
    "capabilityRefs",
    "publicKeyFingerprint",
    "signerRef",
    "validFrom",
    "validUntil",
    "version",
    "signature",
  ],
  properties: {
    serviceRef: { type: "string", minLength: 1 },
    handle: { type: "string", minLength: 1 },
    transport: { type: "string", enum: transports },
    endpoint: { type: "string", minLength: 1 },
    capabilityRefs: stringArray,
    publicKeyFingerprint: { type: "string", pattern: "^sha256:[a-f0-9]{64}$" },
    signerRef: { type: "string", minLength: 1 },
    validFrom: { type: "string" },
    validUntil: { type: "string" },
    version: { type: "integer", minimum: 1 },
    signature: { type: "string", minLength: 1 },
  },
} as const;

export const channelSchemas = {
  "channel-v1.schema.json": channelV1Schema,
  "header-board-v1.schema.json": headerBoardV1Schema,
  "publication-admission-v1.schema.json": publicationAdmissionV1Schema,
  "publication-receipt-v1.schema.json": publicationReceiptV1Schema,
  "service-route-v1.schema.json": serviceRouteV1Schema,
  "service-descriptor-v1.schema.json": serviceDescriptorV1Schema,
} as const;
