from enum import StrEnum


class WorkPacketState(StrEnum):
    DRAFT = "DRAFT"
    REQUIREMENTS_COMPILED = "REQUIREMENTS_COMPILED"
    INPUTS_READY = "INPUTS_READY"
    AUTHORITY_VERIFIED = "AUTHORITY_VERIFIED"
    ASSIGNED = "ASSIGNED"
    ACCEPTED = "ACCEPTED"
    IN_PROGRESS = "IN_PROGRESS"
    SUBMITTED = "SUBMITTED"
    EVIDENCE_VALIDATION = "EVIDENCE_VALIDATION"
    EFFECT_VERIFICATION = "EFFECT_VERIFICATION"
    CLOSED = "CLOSED"
    BLOCKED = "BLOCKED"


class AuthorityDecisionType(StrEnum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    CONDITIONAL = "CONDITIONAL"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class WardenDecisionType(StrEnum):
    ALLOW = "ALLOW"
    DENY = "DENY"
    CONDITIONAL = "CONDITIONAL"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class EvidenceLevel(StrEnum):
    E0_ASSERTION = "E0"
    E1_SOURCE_DOCUMENT = "E1"
    E2_EXECUTED_INSTRUMENT = "E2"
    E3_PROFESSIONAL_VALIDATION = "E3"
    E4_EXTERNAL_RECEIPT = "E4"
    E5_AUTHORITATIVE_STATE = "E5"
    E6_EFFECT_VERIFIED = "E6"


class EffectResult(StrEnum):
    MATCH = "MATCH"
    NOT_YET_VISIBLE = "NOT_YET_VISIBLE"
    MISMATCH = "MISMATCH"
    REJECTED = "REJECTED"
    UNKNOWN = "UNKNOWN"


class ProfessionalConclusion(StrEnum):
    CONFIRMED = "CONFIRMED"
    COMPLIANT = "COMPLIANT"
    NON_COMPLIANT = "NON_COMPLIANT"
    FILED = "FILED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    REMEDIATION_REQUIRED = "REMEDIATION_REQUIRED"
    UNABLE_TO_CONCLUDE = "UNABLE_TO_CONCLUDE"


class AuthorityType(StrEnum):
    CORPORATE_ACTION = "CORPORATE_ACTION"
    CONTRACT_EXECUTION = "CONTRACT_EXECUTION"
    FILING = "FILING"
    BANKING = "BANKING"


class ActionType(StrEnum):
    PROFESSIONAL_FILING = "PROFESSIONAL_FILING"
    CORPORATE_STATE_CHANGE = "CORPORATE_STATE_CHANGE"
    INSTRUMENT_EXECUTION = "INSTRUMENT_EXECUTION"


class PacketType(StrEnum):
    CORPORATE_MASTER_RECONCILIATION = "CORPORATE_MASTER_RECONCILIATION"
    CORPORATE_STATE_CHANGE = "CORPORATE_STATE_CHANGE"
    INSTRUMENT_EXECUTION = "INSTRUMENT_EXECUTION"


class EvidenceSourceType(StrEnum):
    COMPANY_RECORD = "COMPANY_RECORD"
    PROFESSIONAL = "PROFESSIONAL"
    REGULATOR = "REGULATOR"
    EXTERNAL_SYSTEM = "EXTERNAL_SYSTEM"
    ARC = "ARC"


class DecisionValidityState(StrEnum):
    VALID = "VALID"
    EXPIRED = "EXPIRED"
    RE_ADMISSION_REQUIRED = "RE_ADMISSION_REQUIRED"
    DENIED = "DENIED"
